// pnpm world <command>
//
// Runs under ELECTRON_RUN_AS_NODE, which is what makes 30 accounts cheap: the
// shell's library, keyring and store need Electron's native ABI but not its
// browser, so one plain Node process can hold all thirty.

import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { Keyring } from '../../src/shell/keyring/index.js'
import { ACCOUNTS_DIR, WORLD_DIR, WORLD_JSON, accountDir, closeAll, openAccount, openAll } from './account.js'
import { bySlug, deriveRoster } from './roster.js'
import { buildWorld } from './scenario.js'

const log = (s = ''): void => {
  process.stdout.write(`${s}\n`)
}

function requireSoftwareKeys(): void {
  // The harness writes identity files; without this the keyring would try the
  // OS keychain, which is neither available headless nor wanted for 30
  // throwaway keys.
  if (process.env.SHELL_FORCE_SOFTWARE_KEYS !== '1') {
    throw new Error('SHELL_FORCE_SOFTWARE_KEYS=1 is required — run this through `pnpm world`, not directly')
  }
}

function provision(argv: string[]): void {
  requireSoftwareKeys()
  const force = argv.includes('--force')
  const roster = deriveRoster()
  mkdirSync(ACCOUNTS_DIR, { recursive: true })
  let made = 0
  for (const who of roster) {
    const dir = accountDir(who.slug)
    const identity = join(dir, 'identity.key.enc')
    if (existsSync(identity) && !force) continue
    mkdirSync(dir, { recursive: true })
    Keyring.writeIdentity(dir, who.privkey)
    made++
  }
  writeFileSync(
    WORLD_JSON,
    `${JSON.stringify(
      {
        note: 'Generated by `pnpm world provision`. Derived from a HARDCODED DEV mnemonic — never put anything of value here.',
        accounts: roster.map((a) => ({ slug: a.slug, name: a.name, role: a.role, address: a.address, index: a.index }))
      },
      null,
      2
    )}\n`
  )
  log(`provisioned ${made} new account${made === 1 ? '' : 's'} (${roster.length} total) in ${ACCOUNTS_DIR}`)
  log(`roster written to ${WORLD_JSON}`)
  if (made === 0) log('nothing new — pass --force to rewrite identity files')
}

async function seed(): Promise<void> {
  requireSoftwareKeys()
  const accounts = openAll()
  try {
    log(`building the world across ${accounts.length} accounts…`)
    await buildWorld(accounts, log)
    log('')
    log('done. Try:  pnpm world show ada    or    pnpm world open ada')
  } finally {
    closeAll(accounts)
  }
}

function ls(): void {
  const roster = deriveRoster()
  const provisioned = roster.filter((a) => existsSync(join(accountDir(a.slug), 'identity.key.enc')))
  log(`${provisioned.length}/${roster.length} accounts provisioned in ${ACCOUNTS_DIR}`)
  log('')
  for (const who of roster) {
    const dir = accountDir(who.slug)
    let count = ''
    if (existsSync(join(dir, 'library'))) {
      try {
        const a = openAccount(who)
        try {
          count = `${a.library.feed({ limit: 10_000 }).length} things`
        } finally {
          a.close()
        }
      } catch (e) {
        count = `(${(e as Error).message.split('\n')[0]})`
      }
    } else {
      count = 'not provisioned'
    }
    log(`  ${who.slug.padEnd(11)} ${who.name.padEnd(22)} ${who.address.slice(0, 10)}…  ${count}`)
  }
}

function show(slug: string): void {
  const who = bySlug(deriveRoster(), slug)
  const a = openAccount(who)
  try {
    log(`${who.name} — ${who.role}`)
    log(`  key ${who.address}`)
    log(`  dir ${a.dir}`)
    log('')

    const tribe = a.library.tribe('eth-eip191', who.address)
    log(`tribe (${tribe.size} keys reachable from your own vouches)`)
    const names = new Map(deriveRoster().map((r) => [`eth-eip191:${r.address}`, r.name]))
    for (const [id, seat] of [...tribe].sort((x, y) => x[1].hops - y[1].hops)) {
      const via = seat.via.length > 0 ? ` via ${seat.via.map((k) => names.get(`eth-eip191:${k}`) ?? k.slice(0, 8)).join(' → ')}` : ''
      log(`  ${seat.hops} hop${seat.hops === 1 ? ' ' : 's'}  ${names.get(id) ?? id}${via}`)
    }
    if (tribe.size === 0) log('  (nobody — this account has vouched for no one)')
    log('')

    const rows = a.library.feed({ limit: 200 })
    log(`feed (${rows.length} things)`)
    for (const row of rows.slice(0, 25)) {
      const author = names.get(`eth-eip191:${row.authorKey}`) ?? row.authorKey.slice(0, 10)
      let extra = ''
      if (row.cosignable) {
        const doc = a.library.namedSigners(row.manifestHash)
        const sigs = a.library.signaturesOf(row.manifestHash)
        const signedNamed = doc.filter((n) => sigs.some((s) => s.authorKey === n.key)).length
        const unnamed = sigs.filter((s) => !doc.some((n) => n.key === s.authorKey)).length
        extra = `  [${signedNamed} of ${doc.length} signed${unnamed > 0 ? `, plus ${unnamed} not named` : ''}]`
      }
      const atts = a.library.countRefsTo(row.envelopeHash, 'attests')
      if (atts > 0) {
        const inTribe = a.library
          .feed({ attests: row.envelopeHash, limit: 200 })
          .filter((r) => tribe.has(`${r.authorScheme}:${r.authorKey}`)).length
        extra += `  [${atts} attestation${atts === 1 ? '' : 's'}, ${inTribe} from your tribe]`
      }
      log(`  ${row.type.padEnd(12)} by ${author.padEnd(22)}${extra}`)
    }
    if (rows.length > 25) log(`  … and ${rows.length - 25} more`)
  } finally {
    a.close()
  }
}

function reset(): void {
  if (!existsSync(WORLD_DIR)) {
    log(`nothing to remove — ${WORLD_DIR} does not exist`)
    return
  }
  rmSync(WORLD_DIR, { recursive: true, force: true })
  log(`removed ${WORLD_DIR}`)
  log('re-provisioning from the same mnemonic reproduces identical addresses.')
}

function usage(): void {
  log('pnpm world <command>')
  log('')
  log('  provision [--force]   create the 30 accounts (identity files + roster)')
  log('  seed                  build the scenario across them')
  log('  ls                    the roster, addresses, and how much each holds')
  log('  show <slug>           one account: its tribe and its feed')
  log('  open <slug>           launch the real GUI on that account')
  log('  live <slug>...        launch real instances and hold them open')
  log('  magnet [--from ada] [--to grace] [--timeout 180000]')
  log('                        seed a fresh thing on one and fetch it on the other')
  log('  forum  [--as ada] [--vs linus]')
  log('                        the same forum, ranked in two libraries')
  log('  relay  [--from ada] [--to grace] [--relay wss://…]')
  log('                        post a thing on one; receive it on the other, unasked')
  log('                        --big posts over the inline cap, so it travels as a')
  log('                        pointer and has to be fetched on purpose')
  log('  reset                 delete world/ entirely')
}

async function main(): Promise<void> {
  const [command, ...rest] = process.argv.slice(2)
  switch (command) {
    case 'provision':
      provision(rest)
      break
    case 'seed':
      await seed()
      break
    case 'ls':
      ls()
      break
    case 'show':
      if (!rest[0]) throw new Error('show needs an account slug, e.g. `pnpm world show ada`')
      show(rest[0])
      break
    case 'forum': {
      const { runForum } = await import('./forum.js')
      await runForum(rest)
      break
    }
    case 'relay': {
      const { runRelay } = await import('./relay.js')
      await runRelay(rest)
      break
    }
    case 'magnet': {
      const { runMagnet } = await import('./magnet.js')
      await runMagnet(rest)
      break
    }
    case 'open':
    case 'live': {
      const { runLive } = await import('./live.js')
      await runLive(command, rest)
      break
    }
    case 'reset':
      reset()
      break
    default:
      usage()
      if (command !== undefined && command !== 'help' && command !== '--help') process.exitCode = 1
  }
}

main().catch((e: unknown) => {
  log(`error: ${(e as Error).message}`)
  process.exitCode = 1
})
